### ISSUE TITLE
K1_EuclideanLoss has two input

### ISSUE THREAD

**Issue by appleleaves** [kevinlin311tw/Caffe-DeepBinaryCode#11]
Hi Kevin:
Why K1_EuclideanLoss and K2_EuclideanLoss has two same input?
I believe you are doing the same work on both input, in SSDH case, the latent_sigmoid layer output.
Why? Am I wrong,or miss something?

Thanks for your time.

-Yip

**Comment by kevinlin311tw** [comment]
The second input is just a redundant input. We compute loss only with the first input. Any pull-requests are welcome!
