### ISSUE TITLE
multi-label classification loss?

### ISSUE THREAD

**Issue by wendalegood** [kevinlin311tw/Caffe-DeepBinaryCode#12]
Hi, kevin
I can't figure out where did you use multi-label classification loss as you mentioned in your paper(formula (5)). I check all your trainval.prototxt about SSDH and find nothing about using multi-label, all your classification loss is softmaxwithloss. thx.

**Comment by kevinlin311tw** [comment]
The multi-label version is not uploaded yet. We plan to release the code in future.

**Comment by wendalegood** [comment]
what is the difference of precision@k when use multi-label and multi-class version respectively? Did multi-label version have good performance? If it is, how much? thanks a lot.

**Comment by kevinlin311tw** [comment]
You may check our multi-label results on NUS-WIDE and UT-ZAP50K datasets. 
Please note that multi-label and single-label (or multi-class) are fundamentally different tasks. We cannot compare their performance.
