### ISSUE TITLE
How can I train on some new CNNs such as Resnet or inception?

### ISSUE THREAD

**Issue by akturtle** [kevinlin311tw/Caffe-DeepBinaryCode#17]
Since vgg is a old CNN structure, if it possible i train your method on some new cnns?  And How?

**Comment by kevinlin311tw** [comment]
Embed the latent layer + sigmoid layer between the last fully-connected layer and the classification layer. Then, employ the objective function to learn binary codes.

**Comment by akturtle** [comment]
The sigmoid layer seems introduces the gradient vanish problem. It seems not work for deeper CNN structure. Have you tested on incepetion or resnet?

**Comment by kevinlin311tw** [comment]
I didn't implement SSDH on RestNet and GoogLeNet. So, I am not quite sure how the gradient vanish problem affect the deep hashing. However, perhaps you can start with ResNet50. According to recent arXiv papers, a few well-known tech companies have implemented SSDH on ResNet50 for their products, and it works very well.

**Comment by akturtle** [comment]
Hi, thanks for your reply. I'm trying to implement  SSDH with MXnet. Could you kindly give me the above paper on arXiv?

**Comment by kevinlin311tw** [comment]
You may find the arxiv here: https://arxiv.org/abs/1706.03154
