### ISSUE TITLE
Can not understand the definition in the paper

### ISSUE THREAD

**Issue by sunyinhui** [kevinlin311tw/Caffe-DeepBinaryCode#2]
Let I = {I n } n=1 be the N images and Y = {y n }
be their associated label vectors, where M denotes the total
number of class labels. An entry of y n is 1 if an image I n
belongs to the corresponding class and 0 otherwise.

**Comment by sunyinhui** [comment]
what's the y？ like y={0,1,0,0....} or others ?

**Comment by kevinlin311tw** [comment]
Yes. y_{n} is the label vector.

For example, let the category of image I_{k} be the "beer", then 

```
                        apple    beer   cake   donuts     ...
           y_{k} = {       0,       1,      0,      0, ...}
```

**Comment by sunyinhui** [comment]
I understand ,Thanks! Can you tell me more detial about argmin L(yn, yn)+||W|| ?  thanks a lot!

**Comment by kevinlin311tw** [comment]
That is the standard softmax loss.

**Comment by sunyinhui** [comment]
Thanks!
