### ISSUE TITLE
Still getting 10% MAP with Cifar10

### ISSUE THREAD

**Issue by aprix** [kevinlin311tw/Caffe-DeepBinaryCode#20]
Hey, when you guys say that one should launch matlab at caffe's root folder, what exactly do you mean?
I've done all that is suggested but still get 10% MAP when I execute the run_cifar10 code. :/
Any other things that I should do you could think of?

**Comment by kevinlin311tw** [comment]
Hope this may help: https://github.com/kevinlin311tw/caffe-cvprw15/issues/17
