### ISSUE TITLE
Where can I find the implementation of your objective functions?

### ISSUE THREAD

**Issue by sunyinhui** [kevinlin311tw/Caffe-DeepBinaryCode#4]

**Comment by sunyinhui** [comment]
is it written in K1_euclidean_loss_layer.cpp and K2_euclidean_loss_layer.cpp ???   or any others???
thanks !!!

**Comment by kevinlin311tw** [comment]
Yes. 
K1_euclidean_loss_layer.cpp and K2_euclidean_loss_layer.cpp

**Comment by sunyinhui** [comment]
Thanks!!!   Good night  !!!
