### ISSUE TITLE
Can not understand the loss functions

### ISSUE THREAD

**Issue by sunyinhui** [kevinlin311tw/Caffe-DeepBinaryCode#5]
K1_EuclideanLoss will enforce each node in encode_neuron to be 0 or 1.
K2_EuclideanLoss will ensure each node in encode_neuron has a 50% chance of being 0 or 1.
How ??? thanks!!!

**Comment by kevinlin311tw** [comment]
The objectives are described here http://arxiv.org/abs/1507.00101
